run:
  deadline: "3m"
  skip-dirs:
    - pkg/graph

linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - gocritic
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - varcheck
