// gmailctl-config-migrate is a tool to migrate gmailctl YAML configs to the latest version.
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/mbrt/gmailctl/pkg/rimport"
)

const header = `// This file is generated by gmailctl-config-migrate.
//
// WARNING: This functionality is experimental. Before making any
// changes, check that no diff is detected with the remote filters by
// using the 'gmailctl diff' command.
`

func do(path string) error {
	cfg, err := importConfig(path)
	if err != nil {
		return err
	}
	err = rimport.MarshalJsonnet(cfg, os.Stdout, header)
	if err != nil {
		return fmt.Errorf("converting to Jsonnet: %w", err)
	}
	return nil
}

func main() {
	flag.Parse()

	if len(flag.Args()) < 1 {
		fmt.Fprintln(os.Stderr, "No config file specified")
		os.Exit(1)
	}
	for _, path := range flag.Args() {
		if err := do(path); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
	}
}
